import "./globals.css";
import Nav from "./components/nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-[100vh] flex flex-col justify-center items-center">
        {children}
      </body>
    </html>
  );
}
